local builtin = require('telescope.builtin')

vim.keymap.set('n', '<c-p>', builtin.find_files, {})
vim.keymap.set('n', '<Space><Space>', builtin.oldfiles, {})
vim.keymap.set('n', '<Space>fg', builtin.live_grep, {})
vim.keymap.set('n', '<Space>fb', builtin.buffers, {})
vim.keymap.set('n', '<Space>fh', builtin.help_tags, {})
vim.keymap.set('n', '<Space>fc', builtin.commands, {})
vim.keymap.set('n', '<Space>fm', builtin.marks, {})
vim.keymap.set('n', '<Space>fq', builtin.quickfix, {})
vim.keymap.set('n', '<Space>fj', builtin.jumplist, {})
vim.keymap.set('n', '<Space>fr', builtin.registers, {})
vim.keymap.set('n', '<Space>ff', builtin.current_buffer_fuzzy_find, {})
vim.keymap.set('n', '<Space>gc', builtin.git_commits, {})
vim.keymap.set('n', '<Space>gb', builtin.git_branches, {})
vim.keymap.set('n', '<Space>ts', builtin.treesitter, {})
